import { mkdir, readFile, writeFile, copyFile, cp } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const npmCli = process.env.npm_execpath;
if (!npmCli) throw new Error('Ejecuta este script mediante npm run release.');
const dist = path.join(root, 'dist');
await mkdir(dist, { recursive: true });
const result = JSON.parse(execFileSync(process.execPath, [npmCli, 'pack', '--json', '--pack-destination', dist], { cwd: root, encoding: 'utf8' }))[0];
const file = path.join(dist, result.filename);
const metadata = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const sumsName = `GAONA-HUB-${metadata.version}-SHA256SUMS.txt`;
const digest = createHash('sha256').update(await readFile(file)).digest('hex');
await writeFile(path.join(dist, sumsName), `${digest}  ${result.filename}\n`);
const bundle = path.join(dist, `GAONA-HUB-${metadata.version}`);
await mkdir(path.join(bundle, 'scripts'), { recursive: true });
for (const name of [result.filename, sumsName]) await copyFile(path.join(dist, name), path.join(bundle, name));
for (const name of ['README.md', 'LICENSE', 'CHANGELOG.md', 'THIRD-PARTY-NOTICES.txt']) await copyFile(path.join(root, name), path.join(bundle, name));
await cp(path.join(root, 'scripts', 'install.ps1'), path.join(bundle, 'scripts', 'install.ps1'));
await cp(path.join(root, 'docs'), path.join(bundle, 'docs'), { recursive: true });
console.log(`Release preparado: ${bundle}\nPaquete: ${result.filename}\nSHA256: ${digest}`);
